manifest:
  remotes:
    - name: zmkfirmware
      #url-base: https://github.com/ftc/     # <--- CHANGE REPO
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      #revision: mouse-ftc                   # <--- CHANGE REVISION
      revision: main
      import: app/west.yml
  self:
    path: config
